version: '3.8'

services:

  db:
    restart: always
    image: postgres:14.6-alpine
    container_name: mockPay
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    # volumes:
    #   - ./database/postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"